name: Sbom 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  container-scanning: 
    runs-on: ubuntu-latest 
    name: sbom 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Running sbom 
      run : |  
              docker sbom ghcr.io/joshuawe45/juice-app:latest  || true 
