name: Sca 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  bundler: 
    runs-on: ubuntu-latest 
    name: sca
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Perform Npm   
      run : | 
            npm install
            npm i --package-lock-only
            npm config get package-lock
            npm config get shrinkwrap
            npm i --package-lock-only
            npm audit --json  --audit-level=high || true
