name: Run the application
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  run-the-application: 
    runs-on: ubuntu-latest 
    name: Run
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Build the  application 
      run : | 
            docker run --rm -p 3000:3000 joshuawe45/certification:juice
